# Dataset directories
data_dir: '../data'
train_dir: '/data/home/acw723/datasets/fma/fma_small'
# train_dir: 'data/fma_small_all.json'
val_dir: '/data/home/acw723/datasets/fma/fma_medium'
# val_dir: 'data/fma_medium_all.json'
ir_dir: '/data/home/acw723/datasets/ir'
noise_dir: '/data/home/acw723/datasets/musan/noise/'

# Model input parameters
arch: 'ast'
fs: 16000
dur: 1.0
offset: 0.2
norm: 0.95
win_len: 400
hop_len: 161
n_mels: 64
n_fft: 400
silence: 0.0005  # silence threshold


# Dataset and Model hyperparameters
train_sz: 8000
val_sz: 25000
bsz_train: 512
tau: 0.1
lr: 1.0e-4
min_lr: 1.0e-6
n_epochs: 400
T_max: 800
error_threshold: 5

# Augmentation hyperparameters
n_frames: 100 # depends on the spectrogram parameters
overlap: 0.5
tr_snr: [0, 20]
val_snr: [0, 20]
test_snr: [19, 21]
time_mask: 50
freq_mask: 32
noise_prob: 1.0
ir_prob: 1.0

# Model architecture
d: 128
h: 1024
u: 32

# Database sizes (validation)
n_dummy: 100
n_query: 20


  