# Inpute feature extraction parameters (peak picking)


# Below are the default configs from the audfprint work
# fs : 11025
# oversamp: 1
# n_fft : 512
# n_hop : 256
# hpf_pole: 0.98  # spectrogram enhancement
# density: 20.0
# f_sd : 30.0   # how wide to spreak peaks
# maxpksperframe: 5   # maximum number of peaks per frame

fs : 11025
oversamp: 1
n_fft : 512
hop_len : 256
hpf_pole: 0.98  # spectrogram enhancement
density: 100.0
f_sd : 5.0   # how wide to spreak peaks
maxpksperframe: 20   # maximum number of peaks per frame