# Dataset directories
data_dir: 'data'
# train_dir: '/data/home/acw723/datasets/fma/fma_small'
# # train_dir: 'data/fma_small_all.json'
# val_dir: '/data/home/acw723/datasets/fma/fma_medium'
# # val_dir: 'data/fma_medium_all.json'
# ir_dir: '/data/home/acw723/datasets/ir'
# noise_dir: '/data/home/acw723/datasets/musan/noise/'

train_dir: 'data/fma_small_all.json'
val_dir: 'data/fma_medium_all.json'
ir_dir: '/import/research_c4dm/ss380/AIR_1_4' # To-do: Change this
noise_dir: '/import/c4dm-datasets/musan'


# Model input parameters
arch: 'grafp'
fs: 16000
dur: 1.0
offset: 0.2
norm: 0.95
win_len: 1024
hop_len: 512
n_mels: 64
n_fft: 1024
hpf_pole: 0.98  # spectrogram enhancement
density: 250.0
f_sd : 1.0   # how wide to spreak peaks
maxpksperframe: 64   # maximum number of peaks per frame
n_peaks: 512  # max number of peaks to consider
oversamp: 1  # oversample factor for peak detection
silence: 0.0005  # silence threshold
blur_kernel: [7,7]  # blur kernel size
blur_sigma: 3.0  # blur sigma

# Dataset and Model hyperparameters
train_sz: 8000
val_sz: 25000
bsz_train: 128
peak_stride: 2
n_filters : 16 # number of filters in the peak extraction layer
tau: 0.05
lr: 8.0e-5
min_lr: 7.0e-7
n_epochs: 400
T_max: 400
lambda: 0.0
error_threshold: 5

# Augmentation hyperparameters
n_frames: 32 # depends on the spectrogram parameters
overlap: 0.5
tr_snr: [0, 20]
val_snr: [0, 10]
test_snr: [19, 21]
time_mask: 16
freq_mask: 32
noise_prob: 1.0
ir_prob: 1.0

# Model architecture
d: 128
h: 1024
u: 32

# Database sizes (validation)
n_dummy: 100
n_query: 20