# Dataset directories
data_dir: 'data'
train_dir: '/import/c4dm-datasets-ext/fma/fma/data/fma_medium'
# val_dir: 'data/valid'
val_dir: '/import/c4dm-datasets-ext/fma/fma/data/fma_medium'
ir_dir: '/import/research_c4dm/ss380/AIR_1_4' # To-do: Change this
noise_dir: '/import/c4dm-datasets/musan'

# Model input parameters
arch: 'grafp'
fs: 11025
dur: 1.0
offset: 0.05
norm: 0.95
win_len: 400
hop_len: 128
n_mels: 64
n_fft: 512
hpf_pole: 0.98  # spectrogram enhancement
density: 250.0
f_sd : 1.0   # how wide to spreak peaks
maxpksperframe: 64   # maximum number of peaks per frame
n_peaks: 512  # max number of peaks to consider
oversamp: 1  # oversample factor for peak detection
silence: 0.0005  # silence threshold
blur_kernel: 9  # blur kernel size
blur_sigma: 3.0  # blur sigma

# Dataset and Model hyperparameters
train_sz: 15000
val_sz: 500
bsz_train: 256
n_filters : 8 # number of filters in the peak extraction layer
tau: 0.05
lr: 1.0e-4
min_lr: 1.0e-6
n_epochs: 400
T_max: 380
lambda: 0.02

# Augmentation hyperparameters
n_frames: 87 # depends on the spectrogram parameters
overlap: 0.9
tr_snr: [0, 20]
val_snr: [0, 10]
test_snr: [19, 21]
# time_mask: 48
# freq_mask: 32
noise_prob: 1.0
ir_prob: 1.0

# Model architecture
d: 128
h: 1024
u: 32

# Database sizes (validation)
n_dummy: 100
n_query: 20
