# tc_6: [ 200, 140, 'best']
# tc_19: [140,180]
# tc_20: [330, 'best']
# tc_21: [130, 'best']
# tc_22: [320, 'best']
# tc_23: [360, 'best']
# tc_24: [390, 'best']
tc_27: [370]
# tc_29 : ['best']
# tc_30 : ['best']
# tc_31 : [360]
